import { AbsoluteFill, Audio, Composition, Img, interpolate, Sequence, spring, staticFile, useCurrentFrame, useVideoConfig } from "remotion";
import { uiSwitch, whoosh } from "@remotion/sfx";

const PINK = "#f54d9a";
const PINK_SOFT = "#ff9ac8";
const PAPER = "#f2efed";
const MUTED = "#a8a2a6";
const LINE = "rgba(255,255,255,0.14)";
const FONT = "Georgia, 'Times New Roman', serif";
const MONO = "Consolas, 'Courier New', monospace";
const clamp = (value: number) => Math.max(0, Math.min(1, value));
const enter = (frame: number, start: number, length = 18) => spring({ frame: frame - start, fps: 30, config: { damping: 200, stiffness: 130 }, durationInFrames: length });
const fade = (frame: number, start: number, end: number) => clamp(interpolate(frame, [start, start + 10, end - 10, end], [0, 1, 1, 0], { extrapolateLeft: "clamp", extrapolateRight: "clamp" }));

const Dot = ({ color = PINK, size = 8 }: { color?: string; size?: number }) => <span style={{ width: size, height: size, borderRadius: 999, background: color, display: "inline-block", boxShadow: `0 0 ${size * 2}px ${color}` }} />;
const Pill = ({ children, active = false }: { children: React.ReactNode; active?: boolean }) => <div style={{ border: `1px solid ${active ? PINK : LINE}`, borderRadius: 8, padding: "9px 14px", color: active ? PAPER : MUTED, background: active ? "rgba(245,77,154,.1)" : "rgba(255,255,255,.025)", fontFamily: MONO, fontSize: 15, letterSpacing: ".04em" }}>{children}</div>;

const AppShell = ({ mode, children, frame }: { mode: "Chat" | "Swarm" | "Code" | "Work"; children: React.ReactNode; frame: number }) => {
  const { height } = useVideoConfig();
  const inScale = interpolate(enter(frame, 0), [0, 1], [0.985, 1]);
  const tabs = [["Chat", "chat.png"], ["Work", "work.png"], ["Code", "code.png"]] as const;
  return <AbsoluteFill style={{ background: "#0d0d10", fontFamily: FONT, color: PAPER, scale: inScale }}>
    <header style={{ height: 76, borderBottom: `1px solid ${LINE}`, display: "flex", alignItems: "center", padding: "0 26px", fontFamily: MONO, background: "#0c0c0f" }}>
      <div style={{ display: "flex", alignItems: "center", gap: 8 }}>{[["▢", "Chat"], ["□", "Projects"], ["☼", "Models"], ["⚙", "Settings"]].map(([icon, label], index) => <div key={label} style={{ padding: "13px 15px", borderRadius: 7, border: index === 0 ? `1px solid ${LINE}` : "1px solid transparent", borderBottom: index === 0 ? `3px solid ${PINK}` : "1px solid transparent", color: index === 0 ? PAPER : MUTED, fontSize: 17, fontWeight: 700 }}><span style={{ marginRight: 9, color: index === 0 ? PAPER : "#77717a" }}>{icon}</span>{label}</div>)}</div>
      <div style={{ flex: 1 }} /><div style={{ color: MUTED, fontSize: 15, marginRight: 16 }}>Recent chats</div><Pill>Agents</Pill><div style={{ marginLeft: 9, border: `1px solid ${LINE}`, padding: "10px 15px", borderRadius: 7, color: PAPER, fontWeight: 700, fontSize: 15 }}><span style={{ color: PINK, marginRight: 12 }}>WEB</span> Browser</div><div style={{ marginLeft: 24, color: MUTED, letterSpacing: ".25em" }}>— □ ×</div>
    </header>
    <div style={{ display: "flex", height: height - 76 }}><aside style={{ width: 310, borderRight: `1px solid ${LINE}`, padding: "27px 18px 18px", boxSizing: "border-box", background: "#111114", position: "relative" }}>
      <div style={{ display: "flex", gap: 11, alignItems: "center", fontSize: 25, fontWeight: 700, margin: "0 10px 47px" }}><Img src={staticFile("axon-assets/icon.png")} style={{ width: 26, height: 26, objectFit: "contain" }} /><span>Axon</span></div>
      <div style={{ color: MUTED, fontFamily: MONO, fontSize: 14, letterSpacing: ".1em", margin: "0 10px 18px" }}>MODE</div>
      <div style={{ display: "flex", borderBottom: `1px solid ${LINE}`, marginBottom: 13 }}>{tabs.map(([item, asset]) => <div key={item} style={{ flex: 1, textAlign: "center", padding: "0 0 13px", borderBottom: item === (mode === "Swarm" ? "Chat" : mode) ? `3px solid ${PINK}` : "3px solid transparent", color: item === (mode === "Swarm" ? "Chat" : mode) ? PAPER : MUTED, fontSize: 16, fontWeight: 700 }}><Img src={staticFile(`axon-assets/${asset}`)} style={{ width: 23, height: 19, objectFit: "contain", verticalAlign: "middle", marginRight: 5, opacity: item === (mode === "Swarm" ? "Chat" : mode) ? 1 : .55 }} />{item}</div>)}</div>
      <div style={{ border: `1px solid ${LINE}`, borderRadius: 8, padding: "13px 14px", display: "flex", alignItems: "center", gap: 11, background: "rgba(255,255,255,.015)" }}><Img src={staticFile("axon-assets/swarm.png")} style={{ width: 30, height: 30, objectFit: "contain" }} /><div style={{ flex: 1 }}><b style={{ display: "block", fontSize: 17 }}>Axon Swarm</b><span style={{ color: MUTED, fontSize: 14 }}>Parallel independent workers</span></div><span style={{ color: PINK, fontSize: 20 }}>↗</span></div>
      <div style={{ color: MUTED, fontSize: 13, letterSpacing: ".06em", margin: "14px 10px" }}>{mode === "Code" ? "Terminal workspace · tools enabled" : mode === "Work" ? "Outcome-oriented workspace" : "Direct conversation · no tools"}</div><div style={{ border: `1px solid ${LINE}`, borderRadius: 8, padding: "14px 15px", fontSize: 17, marginTop: 12 }}>＋ New chat</div><div style={{ color: MUTED, fontFamily: MONO, fontSize: 14, margin: "27px 10px 12px", letterSpacing: ".08em" }}>RECENT CHATS</div><div style={{ color: "#77717a", fontSize: 15, margin: "0 10px" }}>No chats yet.</div>
      <div style={{ position: "absolute", left: 18, right: 18, bottom: 18, padding: "15px", background: "rgba(255,255,255,.025)", display: "flex", gap: 12, alignItems: "center" }}><div style={{ width: 35, height: 35, border: `1px solid ${PINK}`, color: PINK, borderRadius: 999, display: "grid", placeItems: "center" }}>I</div><div><b style={{ display: "block", fontSize: 15 }}>iyad</b><span style={{ color: MUTED, fontSize: 12 }}>Local only · click to edit</span></div></div>
    </aside><main style={{ position: "relative", flex: 1, overflow: "hidden", background: "#0e0e11" }}>{children}</main></div>
  </AbsoluteFill>;
};

const SceneTitle = ({ eyebrow, title, body, frame, start, end }: { eyebrow: string; title: string; body: string; frame: number; start: number; end: number }) => {
  const visibility = fade(frame, start, end); const y = interpolate(enter(frame, start), [0, 1], [24, 0]);
  return <div style={{ position: "absolute", left: 58, top: 48, opacity: visibility, translate: `0 ${y}px`, zIndex: 5 }}><div style={{ color: PINK, fontFamily: MONO, fontSize: 15, letterSpacing: ".17em", marginBottom: 12 }}>{eyebrow}</div><div style={{ fontSize: 62, letterSpacing: "-.045em", lineHeight: .95, textWrap: "balance", maxWidth: 690 }}>{title}</div><div style={{ fontSize: 22, color: MUTED, marginTop: 17, maxWidth: 570, lineHeight: 1.35 }}>{body}</div></div>;
};

export const ChatScene = ({ frame }: { frame: number }) => { const scene = fade(frame, 25, 185); const prompt = "Map the next release without losing the thread."; const count = Math.floor(interpolate(frame, [88, 142], [0, prompt.length], { extrapolateLeft: "clamp", extrapolateRight: "clamp" })); return <div style={{ opacity: scene }}><SceneTitle frame={frame} start={35} end={175} eyebrow="01 / DIRECT THOUGHT" title="Chat, without the clutter." body="A focused conversation for ideas, decisions, and the next sharp question." /><div style={{ position: "absolute", left: 58, right: 58, bottom: 54, height: 150, border: `1px solid ${LINE}`, background: "#151519", borderRadius: 14, padding: 23, boxSizing: "border-box", fontFamily: MONO, color: PAPER, fontSize: 20 }}><div style={{ color: frame > 145 ? PAPER : "#767079" }}>{prompt.slice(0, count)}<span style={{ color: PINK, opacity: Math.floor(frame / 8) % 2 }}>▌</span></div><div style={{ height: 1, background: LINE, margin: "24px 0 14px" }} /><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}><div style={{ display: "flex", gap: 12, alignItems: "center" }}><Dot color="#5edbb0" /><Pill active>GLM-5.2C</Pill><span style={{ fontSize: 13, color: MUTED }}>TEXT + TOOLS</span></div><div style={{ background: PINK, color: "#1a0a12", padding: "10px 16px", borderRadius: 8, fontWeight: 700 }}>SEND ↗</div></div></div></div>; };

export const SwarmScene = ({ frame }: { frame: number }) => { const scene = fade(frame, 165, 330); const nodes = [["SENTRY", "Synthesis", 1050, 156, PINK], ["SCOUT", "Research", 235, 390, "#7d8bf7"], ["BUILDER", "Implement", 585, 436, "#f3b65d"], ["SKEPTIC", "Challenge", 835, 328, "#65cfac"]] as const; return <div style={{ opacity: scene }}><SceneTitle frame={frame} start={180} end={320} eyebrow="02 / ORCHESTRATE" title="One prompt. A whole field of thought." body="Independent workers scout, build, and challenge — Sentry keeps the synthesis visible." /><svg viewBox="0 0 1560 680" style={{ position: "absolute", inset: 0, width: "100%", height: "100%", opacity: .7 }}>{[[1110, 220, 285, 420], [1110, 195, 635, 466], [1110, 220, 885, 358]].map((line, index) => <line key={index} x1={line[0]} y1={line[1]} x2={line[2]} y2={line[3]} stroke={PINK} strokeWidth="2" strokeDasharray="10 14" strokeDashoffset={-frame * 2} />)}</svg>{nodes.map(([name, job, x, y, color], i) => { const pop = enter(frame, 204 + i * 12); return <div key={name} style={{ position: "absolute", left: x, top: y, width: 180, opacity: pop, scale: interpolate(pop, [0, 1], [.8, 1]), border: `1px solid ${color}`, borderRadius: 13, padding: "18px 17px", background: "rgba(20,20,25,.96)", boxShadow: `0 0 35px ${color}24` }}><div style={{ color, fontFamily: MONO, fontSize: 15, letterSpacing: ".13em" }}>{name}</div><div style={{ fontSize: 23, marginTop: 8 }}>{job}</div><div style={{ marginTop: 14, fontFamily: MONO, fontSize: 12, color: MUTED, display: "flex", gap: 8, alignItems: "center" }}><Dot color={color} size={6} />LIVE / READ-ONLY</div></div>; })}</div>; };

export const CodeScene = ({ frame }: { frame: number }) => { const scene = fade(frame, 310, 475); const lines = ["$ axon code release-audit", "▸ Axon Terminal · custom Codex fork", "▸ isolated AXON_HOME + project MCP", "✓ 12 checks passed", "", "review: provider-picker.ts", "  + native provider profiles", "  + bounded Cloud-tool bridge", "", "ready for your approval_ "]; return <div style={{ opacity: scene }}><SceneTitle frame={frame} start={328} end={465} eyebrow="03 / THE CUSTOM HARNESS" title="A forked harness. Native to Axon." body="Code runs through Axon Terminal: an isolated, custom fork with its own state, MCP, and workspace context." /><div style={{ position: "absolute", left: 58, right: 58, bottom: 48, height: 280, background: "#0b0d10", border: "1px solid #34343c", borderRadius: 12, overflow: "hidden", fontFamily: MONO, padding: "20px 26px", boxSizing: "border-box", fontSize: 19, lineHeight: 1.55 }}><div style={{ display: "flex", gap: 8, marginBottom: 12 }}><Dot color="#ff6c8d" /><Dot color="#f2ba5b" /><Dot color="#5dd4a9" /><span style={{ color: "#69656b", marginLeft: 10, fontSize: 14 }}>AXON TERMINAL / CUSTOM FORK</span></div>{lines.map((line, index) => <div key={`${line}-${index}`} style={{ color: line.startsWith("✓") ? "#65cfac" : line.startsWith("▸") ? "#91a1ff" : line.startsWith("  +") ? PAPER : index === 0 ? PINK_SOFT : "#c3bdc4", opacity: enter(frame, 360 + index * 9) }}>{line}</div>)}</div></div>; };

export const WorkScene = ({ frame }: { frame: number }) => { const scene = fade(frame, 455, 610); const tasks = [["Frame the decision", "DONE"], ["Probe provider fit", "IN PROGRESS"], ["Draft release plan", "QUEUED"]]; return <div style={{ opacity: scene }}><SceneTitle frame={frame} start={470} end={600} eyebrow="04 / MOVE THE WORK" title="Work is an outcome, not another chat." body="Turn a fuzzy brief into a visible plan, then keep momentum without losing the evidence." /><div style={{ position: "absolute", left: 58, right: 58, bottom: 54, display: "flex", gap: 14 }}>{tasks.map(([task, status], index) => { const up = enter(frame, 492 + index * 15); return <div key={task} style={{ flex: 1, minHeight: 190, boxSizing: "border-box", padding: 20, border: `1px solid ${index === 1 ? PINK : LINE}`, background: index === 1 ? "rgba(245,77,154,.08)" : "rgba(255,255,255,.025)", opacity: up, translate: `0 ${interpolate(up, [0, 1], [22, 0])}px` }}><div style={{ color: index === 1 ? PINK : MUTED, fontFamily: MONO, fontSize: 13, letterSpacing: ".1em" }}>{`0${index + 1}`}</div><div style={{ fontSize: 27, lineHeight: 1.05, marginTop: 17 }}>{task}</div><div style={{ color: index === 0 ? "#65cfac" : index === 1 ? PINK_SOFT : MUTED, fontFamily: MONO, fontSize: 12, marginTop: 28 }}>{status}</div></div>; })}</div></div>; };

const ModelsScene = ({ frame }: { frame: number }) => { const scene = fade(frame, 590, 660); const pop = enter(frame, 610, 22); return <div style={{ opacity: scene }}><div style={{ position: "absolute", inset: 0, background: "rgba(6,6,8,.7)", zIndex: 2 }} /><div style={{ position: "absolute", left: 60, top: 55, zIndex: 4, opacity: enter(frame, 600) }}><div style={{ color: PINK, fontFamily: MONO, fontSize: 15, letterSpacing: ".17em" }}>05 / CHOOSE YOUR INTELLIGENCE</div><div style={{ fontSize: 60, marginTop: 15, letterSpacing: "-.045em" }}>Every model. Every provider.<br />One clean control surface.</div></div><div style={{ position: "absolute", right: 70, bottom: 65, width: 525, zIndex: 5, padding: 19, borderRadius: 14, border: `1px solid ${PINK}`, background: "#19171c", opacity: pop, scale: interpolate(pop, [0, 1], [.92, 1]), boxShadow: "0 25px 90px rgba(0,0,0,.65)" }}><div style={{ color: MUTED, fontFamily: MONO, letterSpacing: ".12em", fontSize: 13, marginBottom: 10 }}>MODEL + PROVIDER</div><div style={{ display: "flex", justifyContent: "space-between", border: `1px solid ${LINE}`, padding: "15px 16px", borderRadius: 8, fontFamily: MONO, fontSize: 18 }}><span><Dot color="#5edbb0" size={9} />&nbsp; qwen3.5:397b-cloud</span><span style={{ color: PINK }}>⌄</span></div><div style={{ marginTop: 10, border: `1px solid ${LINE}`, borderRadius: 8, overflow: "hidden", fontFamily: MONO, fontSize: 16 }}>{["Ollama · local runtime", "OpenAI Responses · connected", "OpenRouter · compatible API"].map((item, index) => <div key={item} style={{ padding: "13px 15px", color: index === 0 ? PAPER : MUTED, background: index === 0 ? "rgba(245,77,154,.12)" : "transparent", borderBottom: index < 2 ? `1px solid ${LINE}` : "none" }}>{index === 0 && <span style={{ color: PINK }}>● </span>}{item}</div>)}</div></div></div>; };

export { ModelsScene };
const Kicker = ({ children }: { children: React.ReactNode }) => <div style={{ color: PINK, fontFamily: MONO, fontSize: 14, letterSpacing: ".16em" }}>{children}</div>;

export const CleanChat = ({ frame }: { frame: number }) => {
  const opacity = fade(frame, 20, 178); const message = "Build a release plan that respects the real constraints.";
  const typed = message.slice(0, Math.floor(interpolate(frame, [45, 94], [0, message.length], { extrapolateLeft: "clamp", extrapolateRight: "clamp" })));
  return <div style={{ opacity }}><div style={{ position: "absolute", left: 78, top: 65 }}><Kicker>CHAT / DIRECT LINE</Kicker><div style={{ fontSize: 44, marginTop: 14, letterSpacing: "-.04em" }}>Thinking stays human.</div></div>
    <div style={{ position: "absolute", left: 78, right: 88, top: 205, bottom: 72, borderTop: `1px solid ${LINE}`, borderBottom: `1px solid ${LINE}` }}>
      <div style={{ position: "absolute", left: 0, top: 55, width: 530, fontSize: 31, lineHeight: 1.25 }}>{typed}<span style={{ color: PINK, opacity: Math.floor(frame / 7) % 2 }}>▌</span></div>
      <div style={{ position: "absolute", right: 0, top: 42, width: 540, paddingLeft: 36, borderLeft: `2px solid ${PINK}`, opacity: enter(frame, 102), translate: `0 ${interpolate(enter(frame, 102), [0, 1], [24, 0])}px` }}><Kicker>AXON / RESPONSE</Kicker><div style={{ fontSize: 28, lineHeight: 1.32, marginTop: 13 }}>I’ll map the goal, inspect the workspace, and show the trade-offs before I move the work forward.</div><div style={{ display: "flex", gap: 20, marginTop: 36, fontFamily: MONO, color: MUTED, fontSize: 14 }}><span><Dot color="#5edbb0" size={7} /> GLM-5.2C</span><span>CONTEXT READY</span></div></div>
      <div style={{ position: "absolute", left: 0, right: 0, bottom: 30, display: "flex", alignItems: "center", justifyContent: "space-between", fontFamily: MONO }}><span style={{ color: MUTED, fontSize: 14 }}>ASK / EXPLORE / DECIDE</span><div style={{ width: 310, height: 3, background: "#27242a", overflow: "hidden" }}><div style={{ width: `${interpolate(frame, [25, 165], [0, 100], { extrapolateLeft: "clamp", extrapolateRight: "clamp" })}%`, height: "100%", background: PINK }} /></div></div>
    </div></div>;
};

export const SignalSwarm = ({ frame }: { frame: number }) => {
  const opacity = fade(frame, 160, 330); const pulse = (offset: number) => (frame * 1.7 + offset) % 100;
  const branches = [[770, 455, 230, 270, "#7b8cff"], [770, 455, 505, 690, "#f5ba61"], [770, 455, 1080, 645, "#65cdaa"], [770, 455, 1240, 245, PINK]] as const;
  return <div style={{ opacity }}><div style={{ position: "absolute", left: 78, top: 65, zIndex: 2 }}><Kicker>SWARM / SIGNAL FIELD</Kicker><div style={{ fontSize: 44, marginTop: 14, letterSpacing: "-.04em" }}>A system that thinks in parallel.</div><div style={{ color: MUTED, fontSize: 19, marginTop: 14 }}>Sentry holds the thread. Workers extend it.</div></div>
    <svg viewBox="0 0 1560 1000" style={{ position: "absolute", inset: 0, width: "100%", height: "100%" }}><defs><filter id="glow"><feGaussianBlur stdDeviation="7" result="blur" /><feMerge><feMergeNode in="blur" /><feMergeNode in="SourceGraphic" /></feMerge></filter></defs>{branches.map(([x1, y1, x2, y2, color], index) => <g key={color}><path d={`M ${x1} ${y1} C ${x1 + (x2 - x1) * .16} ${y1 + (y2 - y1) * .75}, ${x1 + (x2 - x1) * .72} ${y1 - (y2 - y1) * .2}, ${x2} ${y2}`} fill="none" stroke={color} strokeWidth="1.5" opacity=".5" /><circle cx={x1 + (x2 - x1) * (pulse(index * 23) / 100)} cy={y1 + (y2 - y1) * (pulse(index * 23) / 100)} r="7" fill={color} filter="url(#glow)" /></g>)}<circle cx="770" cy="455" r={interpolate(frame, [180, 230], [40, 88], { extrapolateLeft: "clamp", extrapolateRight: "clamp" })} fill="none" stroke={PINK} strokeWidth="1" opacity=".45" /><circle cx="770" cy="455" r="32" fill="#171218" stroke={PINK} strokeWidth="2" filter="url(#glow)" />{branches.map(([, , x, y, color], index) => <g key={`${x}-${y}`} opacity={enter(frame, 190 + index * 10)}><circle cx={x} cy={y} r="19" fill="#141419" stroke={color} strokeWidth="1.5" /><circle cx={x} cy={y} r="5" fill={color} /></g>)}</svg>
    <Img src={staticFile("axon-assets/swarm.png")} style={{ position: "absolute", left: 744, top: 429, width: 52, height: 52, objectFit: "contain" }} /><div style={{ position: "absolute", left: 730, top: 530, fontFamily: MONO, fontSize: 13, color: PINK, letterSpacing: ".12em" }}>SENTRY</div>{[[205, 305, "SCOUT"], [472, 731, "BUILDER"], [1043, 688, "SKEPTIC"], [1186, 279, "SYNTHESIS"]].map(([x, y, label]) => <div key={String(label)} style={{ position: "absolute", left: x as number, top: y as number, fontFamily: MONO, color: MUTED, fontSize: 13, letterSpacing: ".12em" }}>{label as string}</div>)}</div>;
};

export const CodeCanvas = ({ frame }: { frame: number }) => { const opacity = fade(frame, 310, 474); const lines = ["const terminal = fork({", "  home: AXON_HOME,", "  mcp: workspace.tools,", "  provider: selectedProfile", "});"]; return <div style={{ opacity }}><div style={{ position: "absolute", left: 78, top: 65 }}><Kicker>CODE / CUSTOM HARNESS</Kicker><div style={{ fontSize: 44, marginTop: 14, letterSpacing: "-.04em" }}>The harness belongs to the workspace.</div></div><div style={{ position: "absolute", left: 78, right: 88, top: 225, bottom: 75, display: "grid", gridTemplateColumns: "1.08fr .92fr", gap: 1, background: LINE }}><div style={{ background: "#0a0c10", padding: 36, fontFamily: MONO }}><div style={{ color: MUTED, fontSize: 13, letterSpacing: ".12em", marginBottom: 35 }}>AXON TERMINAL / ISOLATED FORK</div><div style={{ color: PINK_SOFT, fontSize: 20 }}>$ axon code provider-audit</div>{["read workspace", "load project MCP", "route via native profile", "checks: passed"].map((line, index) => <div key={line} style={{ marginTop: 18, color: index === 3 ? "#65cdaa" : "#a9b4ff", fontSize: 18, opacity: enter(frame, 346 + index * 10) }}>› {line}</div>)}<div style={{ color: MUTED, marginTop: 58, fontSize: 14 }}>AXON_HOME · OWN CONFIG · OWN MCP</div></div><div style={{ background: "#101015", padding: 36, fontFamily: MONO, overflow: "hidden" }}><div style={{ display: "flex", justifyContent: "space-between", color: MUTED, fontSize: 13, letterSpacing: ".12em", marginBottom: 29 }}><span>provider-bridge.ts</span><span style={{ color: "#65cdaa" }}>+ 5</span></div>{lines.map((line, index) => <div key={line} style={{ color: index === 0 ? PAPER : index === 4 ? "#f5ba61" : "#91a1ff", fontSize: 20, lineHeight: 1.75, opacity: enter(frame, 373 + index * 8), translate: `${interpolate(enter(frame, 373 + index * 8), [0, 1], [-18, 0])}px 0` }}>{line}</div>)}<div style={{ marginTop: 35, height: 2, background: "#2b2630" }}><div style={{ height: "100%", width: "72%", background: PINK }} /></div></div></div></div>; };

export const WorkCanvas = ({ frame }: { frame: number }) => { const opacity = fade(frame, 450, 612); const phases = [["DISCOVER", "Evidence", "#7b8cff"], ["ALIGN", "Decision", PINK], ["EXECUTE", "Momentum", "#65cdaa"]]; return <div style={{ opacity }}><div style={{ position: "absolute", left: 78, top: 65 }}><Kicker>WORK / DECISION FLOW</Kicker><div style={{ fontSize: 44, marginTop: 14, letterSpacing: "-.04em" }}>Turn signal into movement.</div></div><div style={{ position: "absolute", left: 78, right: 88, top: 245, bottom: 95 }}><div style={{ position: "absolute", top: 112, left: 0, right: 0, height: 1, background: LINE }} />{phases.map(([step, detail, color], index) => { const progress = enter(frame, 475 + index * 18); return <div key={step} style={{ position: "absolute", left: `${index * 34}%`, width: "31%", top: 0, opacity: progress }}><div style={{ color, fontFamily: MONO, letterSpacing: ".14em", fontSize: 14 }}>{`0${index + 1} / ${step}`}</div><div style={{ fontSize: 32, marginTop: 24 }}>{detail}</div><div style={{ marginTop: 38, width: 18, height: 18, borderRadius: 999, background: color, boxShadow: `0 0 28px ${color}` }} /><div style={{ fontSize: 18, color: MUTED, lineHeight: 1.35, marginTop: 32, maxWidth: 270 }}>{["Pull the real constraints into view.", "Make the trade-off explicit before acting.", "Keep the next concrete move in motion."][index]}</div></div>})}</div></div>; };

const ModeLabel = ({ children }: { children: React.ReactNode }) => <div style={{ position: "absolute", left: 74, top: 49, color: PINK, font: "700 13px/1 " + MONO, letterSpacing: ".16em" }}>{children}</div>;
const ModeOrb = ({ frame, start, asset, label }: { frame: number; start: number; asset: string; label: string }) => { const flight = clamp(interpolate(frame, [start + 78, start + 110], [0, 1], { extrapolateLeft: "clamp", extrapolateRight: "clamp" })); const textOpacity = interpolate(frame, [start + 25, start + 50, start + 76, start + 88], [0, 1, 1, 0], { extrapolateLeft: "clamp", extrapolateRight: "clamp" }); const beat = 1 + Math.max(0, Math.sin((frame - start - 110) * Math.PI / 18)) * 0.075; return <><Img src={staticFile(`axon-assets/${asset}`)} style={{ position: "absolute", zIndex: 12, left: interpolate(flight, [0, 1], [710, 1460]), top: interpolate(flight, [0, 1], [355, 43]), width: interpolate(flight, [0, 1], [170, 52]), height: interpolate(flight, [0, 1], [170, 52]), objectFit: "contain", opacity: frame < start ? 0 : 1, rotate: `${(frame - start) * 7.5 + flight * 110}deg`, scale: flight > .98 ? beat : 1, filter: "drop-shadow(0 0 24px rgba(245,77,154,.45))" }} /><div style={{ position: "absolute", zIndex: 11, left: 0, right: 0, top: 560, textAlign: "center", opacity: textOpacity, color: PAPER, fontFamily: FONT, fontSize: 46, letterSpacing: "-.035em" }}>{label}</div></>; };

const SimpleChat = ({ frame }: { frame: number }) => <div style={{ opacity: fade(frame, 15, 182) }}><ModeLabel>CHAT</ModeLabel><div style={{ position: "absolute", left: 74, top: 175 }}><Img src={staticFile("axon-assets/icon.png")} style={{ width: 42, height: 42, objectFit: "contain" }} /><div style={{ fontSize: 49, marginTop: 22, letterSpacing: "-.04em" }}>Good afternoon.</div><div style={{ color: MUTED, fontSize: 22, marginTop: 12 }}>What are we working on?</div></div><div style={{ position: "absolute", left: 74, right: 74, bottom: 80, border: `1px solid ${LINE}`, borderRadius: 12, background: "#151519" }}><div style={{ padding: "24px 26px", font: "18px " + MONO, color: "#85808a" }}>Message Axon…</div><div style={{ borderTop: `1px solid ${LINE}`, padding: "14px 18px", display: "flex", alignItems: "center", gap: 14 }}><span style={{ color: MUTED, fontSize: 25 }}>⌇</span><Pill active><Dot color="#5edbb0" size={7} />&nbsp; GLM-5.2C</Pill><span style={{ color: MUTED, font: "13px " + MONO }}>TEXT-ONLY</span><div style={{ flex: 1 }} /><div style={{ width: 44, height: 44, borderRadius: 9, display: "grid", placeItems: "center", background: PINK, color: "#261019" }}>→</div></div></div></div>;

const SimpleSwarm = ({ frame }: { frame: number }) => { const opacity = fade(frame, 170, 326); const rays = [[770,470,330,315,"#7b8cff"],[770,470,520,700,"#f5ba61"],[770,470,1080,670,"#65cdaa"],[770,470,1235,300,PINK]] as const; return <div style={{ opacity }}><ModeLabel>AXON SWARM</ModeLabel><svg viewBox="0 0 1560 1000" style={{ position: "absolute", inset: 0, width: "100%", height: "100%" }}>{rays.map(([x1,y1,x2,y2,color], index) => <g key={color}><path d={`M${x1} ${y1} C${x1+110} ${y1-130},${x2-170} ${y2+100},${x2} ${y2}`} fill="none" stroke={color} strokeWidth="1.5" opacity=".52"/><circle cx={x1+(x2-x1)*(((frame*1.3+index*23)%100)/100)} cy={y1+(y2-y1)*(((frame*1.3+index*23)%100)/100)} r="6" fill={color}/><circle cx={x2} cy={y2} r="14" fill="#121216" stroke={color} strokeWidth="2"/></g>)}<circle cx="770" cy="470" r="78" fill="none" stroke={PINK} strokeWidth="1" opacity=".45"/><circle cx="770" cy="470" r="38" fill="#151117" stroke={PINK} strokeWidth="2"/></svg><Img src={staticFile("axon-assets/swarm.png")} style={{ position: "absolute", left: 738, top: 438, width: 64, height: 64, objectFit: "contain" }} /></div>; };

const SimpleCode = ({ frame }: { frame: number }) => <div style={{ opacity: fade(frame, 315, 472) }}><ModeLabel>CODE</ModeLabel><div style={{ position: "absolute", left: 74, right: 74, top: 150, bottom: 82, background: "#0b0d10", border: `1px solid ${LINE}`, fontFamily: MONO, padding: 31 }}><div style={{ color: MUTED, fontSize: 13, marginBottom: 30 }}>AXON TERMINAL · CUSTOM FORK</div>{["$ axon code provider-audit","› reading workspace","› loading project MCP","✓ check passed","","const route = profile.selected;","await terminal.run(route);"].map((line,index) => <div key={`${line}-${index}`} style={{ fontSize: 21, lineHeight: 1.65, color: line.startsWith("✓") ? "#65cdaa" : line.startsWith("$") ? PINK_SOFT : line.startsWith("const") || line.startsWith("await") ? "#91a1ff" : PAPER, opacity: enter(frame, 340 + index * 9) }}>{line}</div>)}</div></div>;

const SimpleWork = ({ frame }: { frame: number }) => {
  const opacity = fade(frame, 460, 608);
  const browserIn = enter(frame, 476, 22);
  const evidenceIn = enter(frame, 494, 20);
  const actionIn = enter(frame, 515, 20);
  return <div style={{ opacity }}>
    <ModeLabel>WORK / BROWSER</ModeLabel>
    <div style={{ position: "absolute", left: 74, right: 74, top: 142, bottom: 70, border: `1px solid ${LINE}`, borderRadius: 12, overflow: "hidden", background: "#101015", opacity: browserIn, scale: interpolate(browserIn, [0, 1], [.965, 1]) }}>
      <div style={{ height: 50, padding: "0 17px", display: "flex", alignItems: "center", gap: 11, borderBottom: `1px solid ${LINE}`, fontFamily: MONO, color: MUTED, fontSize: 13 }}>
        <span style={{ color: PAPER, fontSize: 21 }}>‹</span><span style={{ color: PAPER, fontSize: 21 }}>›</span><span style={{ fontSize: 17 }}>↻</span>
        <div style={{ flex: 1, padding: "9px 13px", borderRadius: 6, background: "#19191f", color: PAPER }}><span style={{ color: "#65cdaa" }}>◉</span>&nbsp; research.axon.local / provider-brief</div>
        <span style={{ color: PINK, letterSpacing: ".1em" }}>WEB</span>
      </div>
      <div style={{ display: "grid", gridTemplateColumns: "1fr 315px", height: "calc(100% - 50px)" }}>
        <div style={{ padding: "42px 48px", borderRight: `1px solid ${LINE}` }}>
          <div style={{ color: PINK, font: "13px " + MONO, letterSpacing: ".14em" }}>AXON RESEARCH BRIEF</div>
          <div style={{ fontSize: 43, letterSpacing: "-.045em", marginTop: 18, lineHeight: 1.05 }}>Find the right route.<br />Keep the proof.</div>
          <div style={{ marginTop: 34, width: "90%", height: 1, background: LINE }} />
          {["Local runtime keeps sensitive work close.", "Connected providers expand the frontier.", "The decision stays attached to its evidence."].map((line, index) => <div key={line} style={{ display: "flex", gap: 17, alignItems: "center", marginTop: 23, opacity: enter(frame, 487 + index * 12) }}><Dot color={index === 1 ? PINK : "#7b8cff"} size={7} /><span style={{ fontSize: 20, color: index === 2 ? PAPER : MUTED }}>{line}</span></div>)}
        </div>
        <div style={{ padding: 23, background: "#121218" }}>
          <div style={{ color: MUTED, font: "12px " + MONO, letterSpacing: ".12em" }}>EVIDENCE / LIVE</div>
          <div style={{ marginTop: 16, padding: 15, border: `1px solid ${PINK}66`, background: "rgba(245,77,154,.07)", opacity: evidenceIn }}><div style={{ color: PINK_SOFT, font: "13px " + MONO }}>PROVIDER FIT</div><div style={{ fontSize: 22, marginTop: 9 }}>Two viable routes</div><div style={{ color: MUTED, fontSize: 15, marginTop: 8 }}>local + connected</div></div>
          <div style={{ marginTop: 15, padding: 15, border: `1px solid ${LINE}`, opacity: actionIn }}><div style={{ color: "#65cdaa", font: "13px " + MONO }}>NEXT ACTION</div><div style={{ fontSize: 19, marginTop: 9 }}>Draft the release plan</div><div style={{ color: PINK, font: "13px " + MONO, marginTop: 14 }}>OPEN IN WORK →</div></div>
        </div>
      </div>
    </div>
  </div>;
};

const SimpleModels = ({ frame }: { frame: number }) => <div style={{ opacity: fade(frame, 590, 660) }}><ModeLabel>MODELS</ModeLabel><div style={{ position: "absolute", left: 74, top: 175, fontSize: 43, letterSpacing: "-.04em" }}>Choose the route.</div><div style={{ position: "absolute", left: 74, top: 272, width: 625, border: `1px solid ${LINE}`, borderRadius: 9, overflow: "hidden", fontFamily: MONO }}><div style={{ padding: "18px 20px", display: "flex", justifyContent: "space-between", borderBottom: `1px solid ${LINE}` }}><span><Dot color="#5edbb0" size={8}/>&nbsp; qwen3.5:397b-cloud</span><span style={{ color: PINK }}>⌄</span></div>{["Ollama · local runtime","OpenAI Responses · connected","OpenRouter · compatible API"].map((item,index) => <div key={item} style={{ padding: "16px 20px", color: index === 0 ? PAPER : MUTED, background: index === 0 ? "rgba(245,77,154,.1)" : "transparent", borderBottom: index < 2 ? `1px solid ${LINE}` : "none" }}>{item}</div>)}</div></div>;

const NeuralSwarm = ({ frame }: { frame: number }) => {
  const opacity = fade(frame, 170, 326);
  const workers = [[272,288,"#7b8cff","SCOUT","surfaces context"],[470,690,"#f5ba61","BUILDER","makes the move"],[1090,675,"#65cdaa","SKEPTIC","tests the edge"],[1260,295,"#d78cff","OBSERVER","keeps watch"]] as const;
  const coreX = 770, coreY = 470;
  return <div style={{ opacity }}>
    <ModeLabel>AXON SWARM</ModeLabel>
    <div style={{ position: "absolute", left: 74, top: 118, color: MUTED, fontSize: 19 }}>One Sentry brain. Workers as live branches.</div>
    <svg viewBox="0 0 1560 1000" style={{ position:"absolute", inset:0, width:"100%", height:"100%" }}>
      <defs><filter id="sentry-glow"><feGaussianBlur stdDeviation="6" result="blur"/><feMerge><feMergeNode in="blur"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs>
      {[0,1,2].map(ring => <circle key={ring} cx={coreX} cy={coreY} r={70 + ring * 27 + Math.sin((frame + ring * 13) / 10) * 3} fill="none" stroke={PINK} strokeWidth={ring === 0 ? 1.8 : 1} opacity={.5 - ring * .12}/>) }
      {workers.map(([x,y,color,name,detail], index) => { const t = ((frame * .82 + index * 27) % 100) / 100; const cx = coreX + (x - coreX) * t; const cy = coreY + (y - coreY) * t; return <g key={name} opacity={enter(frame, 188 + index * 12)}>
        <path d={`M${coreX} ${coreY} C ${coreX + (x-coreX)*.22} ${coreY + (y-coreY)*.7}, ${coreX + (x-coreX)*.78} ${coreY + (y-coreY)*.1}, ${x} ${y}`} fill="none" stroke={color} strokeWidth="1.7" opacity=".68"/>
        <path d={`M${coreX} ${coreY} C ${coreX + (x-coreX)*.16} ${coreY + (y-coreY)*.42}, ${coreX + (x-coreX)*.62} ${coreY + (y-coreY)*.88}, ${x} ${y}`} fill="none" stroke={color} strokeWidth=".8" opacity=".28"/>
        <circle cx={cx} cy={cy} r="6" fill={color} filter="url(#sentry-glow)"/><circle cx={x} cy={y} r="20" fill="#121217" stroke={color} strokeWidth="1.8"/><circle cx={x} cy={y} r="5" fill={color}/>
        <text x={x + 30} y={y - 8} fill={color} fontFamily="Consolas" fontSize="14" letterSpacing="2">{name}</text><text x={x + 30} y={y + 17} fill="#aaa3ac" fontFamily="Georgia" fontSize="17">{detail}</text>
      </g>; })}
      {[[-145,-55],[142,-50],[-115,105],[120,112],[-32,-150],[36,148]].map(([x,y]) => <g key={`${x}-${y}`} opacity=".5"><path d={`M${coreX + x*.32} ${coreY + y*.32} Q ${coreX+x*.8} ${coreY+y*.18} ${coreX+x} ${coreY+y}`} stroke={PINK_SOFT} strokeWidth="1" fill="none"/><circle cx={coreX+x} cy={coreY+y} r="4" fill={PINK_SOFT}/></g>)}
    </svg>
    <div style={{ position:"absolute", left:coreX-58, top:coreY-58, width:116, height:116, borderRadius:"50%", background:"radial-gradient(circle, #321625 0%, #171116 58%, transparent 62%)", border:`2px solid ${PINK}`, display:"grid", placeItems:"center", boxShadow:"0 0 52px rgba(245,77,154,.33)" }}><Img src={staticFile("axon-assets/swarm.png")} style={{ width:74, height:74, objectFit:"contain" }}/></div>
    <div style={{ position:"absolute", left:coreX-63, top:coreY+76, width:126, textAlign:"center", color:PINK_SOFT, font:"13px "+MONO, letterSpacing:".13em" }}>SENTRY BRAIN</div>
  </div>;
};
const ReelSfx = () => <>
  {[16,170,315,460,592].map((start) => <Sequence key={start} from={start} durationInFrames={18}><Audio src={uiSwitch} volume={0.2} /></Sequence>)}
  {[94,248,393,538].map((start) => <Sequence key={start} from={start} durationInFrames={28}><Audio src={whoosh} volume={0.13} /></Sequence>)}
</>;
export { SimpleSwarm };
export const AxonProductReel: React.FC = () => { const frame = useCurrentFrame(); const mode: "Chat" | "Swarm" | "Code" | "Work" = frame < 185 ? "Chat" : frame < 330 ? "Swarm" : frame < 475 ? "Code" : "Work"; const orb = frame < 185 ? [16,"chat.png","CHAT"] as const : frame < 330 ? [170,"swarm.png","SWARM"] as const : frame < 475 ? [315,"code.png","CODE"] as const : frame < 610 ? [460,"work.png","WORK"] as const : [592,"icon.png","MODELS"] as const; return <AppShell mode={mode} frame={frame}><ReelSfx /><ModeOrb frame={frame} start={orb[0]} asset={orb[1]} label={orb[2]} /><SimpleChat frame={frame} /><NeuralSwarm frame={frame} /><SimpleCode frame={frame} /><SimpleWork frame={frame} /><SimpleModels frame={frame} /></AppShell>; };
export const MyComposition = () => <Composition id="AxonProductReel" component={AxonProductReel} durationInFrames={660} fps={30} width={1920} height={1080} />;
