import { AbsoluteFill, Composition, interpolate, spring, useCurrentFrame, useVideoConfig } from "remotion";

const PINK = "#f54d9a";
const PINK_SOFT = "#ff9ac8";
const PAPER = "#f2efed";
const MUTED = "#a8a2a6";
const LINE = "rgba(255,255,255,0.14)";
const FONT = "Georgia, 'Times New Roman', serif";
const MONO = "Consolas, 'Courier New', monospace";
const clamp = (value: number) => Math.max(0, Math.min(1, value));
const enter = (frame: number, start: number, length = 18) => spring({ frame: frame - start, fps: 30, config: { damping: 200, stiffness: 130 }, durationInFrames: length });
const fade = (frame: number, start: number, end: number) => clamp(interpolate(frame, [start, start + 10, end - 10, end], [0, 1, 1, 0], { extrapolateLeft: "clamp", extrapolateRight: "clamp" }));

const Dot = ({ color = PINK, size = 8 }: { color?: string; size?: number }) => <span style={{ width: size, height: size, borderRadius: 999, background: color, display: "inline-block", boxShadow: `0 0 ${size * 2}px ${color}` }} />;
const Pill = ({ children, active = false }: { children: React.ReactNode; active?: boolean }) => <div style={{ border: `1px solid ${active ? PINK : LINE}`, borderRadius: 8, padding: "9px 14px", color: active ? PAPER : MUTED, background: active ? "rgba(245,77,154,.1)" : "rgba(255,255,255,.025)", fontFamily: MONO, fontSize: 15, letterSpacing: ".04em" }}>{children}</div>;

const AppShell = ({ mode, children, frame }: { mode: "Chat" | "Swarm" | "Code" | "Work"; children: React.ReactNode; frame: number }) => {
  const { width, height } = useVideoConfig();
  const inScale = interpolate(enter(frame, 0), [0, 1], [0.96, 1]);
  return <AbsoluteFill style={{ background: "#09090b", padding: 64, fontFamily: FONT, color: PAPER }}>
    <div style={{ position: "absolute", inset: 0, backgroundImage: "radial-gradient(circle at 22% 10%, rgba(245,77,154,.13), transparent 25%), radial-gradient(circle at 85% 90%, rgba(119,53,138,.14), transparent 28%)" }} />
    <div style={{ position: "relative", width: width - 128, height: height - 128, border: `1px solid ${LINE}`, borderRadius: 18, overflow: "hidden", background: "rgba(13,13,16,.92)", scale: inScale, boxShadow: "0 40px 100px rgba(0,0,0,.5)" }}>
      <div style={{ height: 70, borderBottom: `1px solid ${LINE}`, display: "flex", alignItems: "center", justifyContent: "space-between", padding: "0 28px", fontFamily: MONO }}><div style={{ display: "flex", alignItems: "center", gap: 20 }}><b style={{ color: PINK, fontFamily: FONT, fontSize: 27 }}>✦ Axon</b><span style={{ color: "#68636a" }}>/</span><span style={{ color: PAPER, fontSize: 15 }}>LOCAL-FIRST INTELLIGENCE</span></div><div style={{ display: "flex", gap: 10 }}><Pill>Projects</Pill><Pill>Models</Pill><Pill>Settings</Pill></div></div>
      <div style={{ display: "flex", height: height - 198 }}><aside style={{ width: 232, borderRight: `1px solid ${LINE}`, padding: 25, boxSizing: "border-box", background: "rgba(255,255,255,.012)" }}><div style={{ color: MUTED, fontFamily: MONO, fontSize: 13, letterSpacing: ".12em", marginBottom: 17 }}>WORKSPACE</div>{(["Chat", "Swarm", "Code", "Work"] as const).map((item, index) => <div key={item} style={{ borderLeft: item === mode ? `3px solid ${PINK}` : "3px solid transparent", padding: "12px 10px", marginBottom: 5, color: item === mode ? PAPER : MUTED, fontSize: 21, background: item === mode ? "rgba(245,77,154,.07)" : "transparent" }}><span style={{ color: item === mode ? PINK : "#5d5960", marginRight: 10 }}>{["⌁", "✣", "›_", "↗"][index]}</span>{item}</div>)}<div style={{ height: 1, background: LINE, margin: "28px 0 18px" }} /><div style={{ color: MUTED, fontFamily: MONO, fontSize: 13, letterSpacing: ".12em" }}>RECENT</div><div style={{ color: "#6f6970", marginTop: 17, fontSize: 16, lineHeight: 1.8 }}>Brand system<br />Release notes<br />Repository audit</div></aside><main style={{ position: "relative", flex: 1, overflow: "hidden" }}>{children}</main></div>
    </div>
  </AbsoluteFill>;
};

const SceneTitle = ({ eyebrow, title, body, frame, start, end }: { eyebrow: string; title: string; body: string; frame: number; start: number; end: number }) => {
  const visibility = fade(frame, start, end); const y = interpolate(enter(frame, start), [0, 1], [24, 0]);
  return <div style={{ position: "absolute", left: 58, top: 48, opacity: visibility, translate: `0 ${y}px`, zIndex: 5 }}><div style={{ color: PINK, fontFamily: MONO, fontSize: 15, letterSpacing: ".17em", marginBottom: 12 }}>{eyebrow}</div><div style={{ fontSize: 62, letterSpacing: "-.045em", lineHeight: .95, textWrap: "balance", maxWidth: 690 }}>{title}</div><div style={{ fontSize: 22, color: MUTED, marginTop: 17, maxWidth: 570, lineHeight: 1.35 }}>{body}</div></div>;
};

const ChatScene = ({ frame }: { frame: number }) => { const scene = fade(frame, 25, 185); const prompt = "Map the next release without losing the thread."; const count = Math.floor(interpolate(frame, [88, 142], [0, prompt.length], { extrapolateLeft: "clamp", extrapolateRight: "clamp" })); return <div style={{ opacity: scene }}><SceneTitle frame={frame} start={35} end={175} eyebrow="01 / DIRECT THOUGHT" title="Chat, without the clutter." body="A focused conversation for ideas, decisions, and the next sharp question." /><div style={{ position: "absolute", left: 58, right: 58, bottom: 54, height: 150, border: `1px solid ${LINE}`, background: "#151519", borderRadius: 14, padding: 23, boxSizing: "border-box", fontFamily: MONO, color: PAPER, fontSize: 20 }}><div style={{ color: frame > 145 ? PAPER : "#767079" }}>{prompt.slice(0, count)}<span style={{ color: PINK, opacity: Math.floor(frame / 8) % 2 }}>▌</span></div><div style={{ height: 1, background: LINE, margin: "24px 0 14px" }} /><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}><div style={{ display: "flex", gap: 12, alignItems: "center" }}><Dot color="#5edbb0" /><Pill active>GLM-5.2C</Pill><span style={{ fontSize: 13, color: MUTED }}>TEXT + TOOLS</span></div><div style={{ background: PINK, color: "#1a0a12", padding: "10px 16px", borderRadius: 8, fontWeight: 700 }}>SEND ↗</div></div></div></div>; };

const SwarmScene = ({ frame }: { frame: number }) => { const scene = fade(frame, 165, 330); const nodes = [["SENTRY", "Synthesis", 1050, 156, PINK], ["SCOUT", "Research", 235, 390, "#7d8bf7"], ["BUILDER", "Implement", 585, 436, "#f3b65d"], ["SKEPTIC", "Challenge", 835, 328, "#65cfac"]] as const; return <div style={{ opacity: scene }}><SceneTitle frame={frame} start={180} end={320} eyebrow="02 / ORCHESTRATE" title="One prompt. A whole field of thought." body="Independent workers scout, build, and challenge — Sentry keeps the synthesis visible." /><svg viewBox="0 0 1560 680" style={{ position: "absolute", inset: 0, width: "100%", height: "100%", opacity: .7 }}>{[[1110, 220, 285, 420], [1110, 220, 635, 466], [1110, 220, 885, 358]].map((line, index) => <line key={index} x1={line[0]} y1={line[1]} x2={line[2]} y2={line[3]} stroke={PINK} strokeWidth="2" strokeDasharray="10 14" strokeDashoffset={-frame * 2} />)}</svg>{nodes.map(([name, job, x, y, color], i) => { const pop = enter(frame, 204 + i * 12); return <div key={name} style={{ position: "absolute", left: x, top: y, width: 180, opacity: pop, scale: interpolate(pop, [0, 1], [.8, 1]), border: `1px solid ${color}`, borderRadius: 13, padding: "18px 17px", background: "rgba(20,20,25,.96)", boxShadow: `0 0 35px ${color}24` }}><div style={{ color, fontFamily: MONO, fontSize: 15, letterSpacing: ".13em" }}>{name}</div><div style={{ fontSize: 23, marginTop: 8 }}>{job}</div><div style={{ marginTop: 14, fontFamily: MONO, fontSize: 12, color: MUTED, display: "flex", gap: 8, alignItems: "center" }}><Dot color={color} size={6} />LIVE / READ-ONLY</div></div>; })}</div>; };

const CodeScene = ({ frame }: { frame: number }) => { const scene = fade(frame, 310, 475); const lines = ["$ axon code release-audit", "▸ reading workspace", "▸ testing changed files", "✓ 12 checks passed", "", "review: provider-picker.ts", "  + a model for every route", "  + context that follows the work", "", "ready for your approval_ "]; return <div style={{ opacity: scene }}><SceneTitle frame={frame} start={328} end={465} eyebrow="03 / BUILD IN CONTEXT" title="Code lives in the terminal." body="Its own configuration. Its own tools. The same workspace, without the context switch." /><div style={{ position: "absolute", left: 58, right: 58, bottom: 48, height: 280, background: "#0b0d10", border: "1px solid #34343c", borderRadius: 12, overflow: "hidden", fontFamily: MONO, padding: "20px 26px", boxSizing: "border-box", fontSize: 19, lineHeight: 1.55 }}><div style={{ display: "flex", gap: 8, marginBottom: 12 }}><Dot color="#ff6c8d" /><Dot color="#f2ba5b" /><Dot color="#5dd4a9" /><span style={{ color: "#69656b", marginLeft: 10, fontSize: 14 }}>AXON TERMINAL</span></div>{lines.map((line, index) => <div key={`${line}-${index}`} style={{ color: line.startsWith("✓") ? "#65cfac" : line.startsWith("▸") ? "#91a1ff" : line.startsWith("  +") ? PAPER : index === 0 ? PINK_SOFT : "#c3bdc4", opacity: enter(frame, 360 + index * 9) }}>{line}</div>)}</div></div>; };

const WorkScene = ({ frame }: { frame: number }) => { const scene = fade(frame, 455, 610); const tasks = [["Frame the decision", "DONE"], ["Probe provider fit", "IN PROGRESS"], ["Draft release plan", "QUEUED"]]; return <div style={{ opacity: scene }}><SceneTitle frame={frame} start={470} end={600} eyebrow="04 / MOVE THE WORK" title="Work is an outcome, not another chat." body="Turn a fuzzy brief into a visible plan, then keep momentum without losing the evidence." /><div style={{ position: "absolute", left: 58, right: 58, bottom: 54, display: "flex", gap: 14 }}>{tasks.map(([task, status], index) => { const up = enter(frame, 492 + index * 15); return <div key={task} style={{ flex: 1, minHeight: 190, boxSizing: "border-box", padding: 20, border: `1px solid ${index === 1 ? PINK : LINE}`, background: index === 1 ? "rgba(245,77,154,.08)" : "rgba(255,255,255,.025)", opacity: up, translate: `0 ${interpolate(up, [0, 1], [22, 0])}px` }}><div style={{ color: index === 1 ? PINK : MUTED, fontFamily: MONO, fontSize: 13, letterSpacing: ".1em" }}>{`0${index + 1}`}</div><div style={{ fontSize: 27, lineHeight: 1.05, marginTop: 17 }}>{task}</div><div style={{ color: index === 0 ? "#65cfac" : index === 1 ? PINK_SOFT : MUTED, fontFamily: MONO, fontSize: 12, marginTop: 28 }}>{status}</div></div>; })}</div></div>; };

const ModelsScene = ({ frame }: { frame: number }) => { const scene = fade(frame, 590, 660); const pop = enter(frame, 610, 22); return <div style={{ opacity: scene }}><div style={{ position: "absolute", inset: 0, background: "rgba(6,6,8,.7)", zIndex: 2 }} /><div style={{ position: "absolute", left: 60, top: 55, zIndex: 4, opacity: enter(frame, 600) }}><div style={{ color: PINK, fontFamily: MONO, fontSize: 15, letterSpacing: ".17em" }}>05 / CHOOSE YOUR INTELLIGENCE</div><div style={{ fontSize: 60, marginTop: 15, letterSpacing: "-.045em" }}>Every model. Every provider.<br />One clean control surface.</div></div><div style={{ position: "absolute", right: 70, bottom: 65, width: 525, zIndex: 5, padding: 19, borderRadius: 14, border: `1px solid ${PINK}`, background: "#19171c", opacity: pop, scale: interpolate(pop, [0, 1], [.92, 1]), boxShadow: "0 25px 90px rgba(0,0,0,.65)" }}><div style={{ color: MUTED, fontFamily: MONO, letterSpacing: ".12em", fontSize: 13, marginBottom: 10 }}>MODEL + PROVIDER</div><div style={{ display: "flex", justifyContent: "space-between", border: `1px solid ${LINE}`, padding: "15px 16px", borderRadius: 8, fontFamily: MONO, fontSize: 18 }}><span><Dot color="#5edbb0" size={9} />&nbsp; qwen3.5:397b-cloud</span><span style={{ color: PINK }}>⌄</span></div><div style={{ marginTop: 10, border: `1px solid ${LINE}`, borderRadius: 8, overflow: "hidden", fontFamily: MONO, fontSize: 16 }}>{["Ollama · local runtime", "OpenAI Responses · connected", "OpenRouter · compatible API"].map((item, index) => <div key={item} style={{ padding: "13px 15px", color: index === 0 ? PAPER : MUTED, background: index === 0 ? "rgba(245,77,154,.12)" : "transparent", borderBottom: index < 2 ? `1px solid ${LINE}` : "none" }}>{index === 0 && <span style={{ color: PINK }}>● </span>}{item}</div>)}</div></div></div>; };

export const AxonProductReel: React.FC = () => { const frame = useCurrentFrame(); const mode: "Chat" | "Swarm" | "Code" | "Work" = frame < 185 ? "Chat" : frame < 330 ? "Swarm" : frame < 475 ? "Code" : "Work"; return <AppShell mode={mode} frame={frame}><ChatScene frame={frame} /><SwarmScene frame={frame} /><CodeScene frame={frame} /><WorkScene frame={frame} /><ModelsScene frame={frame} /></AppShell>; };
export const MyComposition = () => <Composition id="AxonProductReel" component={AxonProductReel} durationInFrames={660} fps={30} width={1920} height={1080} />;
