const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('ollama', {
  listModels: () => ipcRenderer.invoke('list-models'),
  listCommands: () => ipcRenderer.invoke('list-commands'),
  fetchCommands: (model) => ipcRenderer.invoke('fetch-commands', model),
  refreshCommands: (model) => ipcRenderer.invoke('refresh-commands', model),
  chat: (model, prompt, sessionId, opts) => ipcRenderer.invoke('chat', { model, prompt, sessionId, ...opts }),
  stop: (requestId) => ipcRenderer.invoke('chat-stop', requestId),
  clear: () => ipcRenderer.invoke('clear'),
  pickFolder: () => ipcRenderer.invoke('pick-folder'),
  ensureWorkspace: () => ipcRenderer.invoke('ensure-workspace'),
  loadState: () => ipcRenderer.invoke('load-state'),
  saveState: (updates) => ipcRenderer.invoke('save-state', updates),
  lanServer: (enabled) => ipcRenderer.invoke('lan-server-toggle', enabled),
  lanConnect: (host) => ipcRenderer.invoke('lan-connect', host),
  lanDisconnect: () => ipcRenderer.invoke('lan-disconnect'),
  lanRefresh: () => ipcRenderer.invoke('lan-discovery-refresh'),
  lanRequestDeviceUpdate: (device) => ipcRenderer.invoke('lan-request-device-update', device),
  selectUpdateInstaller: () => ipcRenderer.invoke('update-select-installer'),
  offerUpdate: () => ipcRenderer.invoke('update-offer'),
  requestUpdate: () => ipcRenderer.invoke('update-request'),
  respondUpdateRequest: (id, approved) => ipcRenderer.invoke('update-respond-request', id, approved),
  acceptUpdateOffer: (id, approved) => ipcRenderer.invoke('update-accept-offer', id, approved),
  openUpdateInstaller: (file) => ipcRenderer.invoke('update-open-installer', file),
  appInfo: () => ipcRenderer.invoke('app-info'),
  installDependencies: () => ipcRenderer.invoke('install-dependencies'),
  cleanupLegacyAxion: () => ipcRenderer.invoke('cleanup-legacy-axion'),
  browserShow: (bounds) => ipcRenderer.invoke('browser-show', bounds),
  browserHide: () => ipcRenderer.invoke('browser-hide'),
  browserNavigate: (url) => ipcRenderer.invoke('browser-navigate', url),
  browserAction: (action) => ipcRenderer.invoke('browser-action', action),
  on: (ch, cb) => { ipcRenderer.on(ch, (_e, v) => cb(v)); },
});
